### ISSUE TITLE
Add user authentication method (SSO) to our management cluster

### ISSUE THREAD

**Issue by ipolonsk** [open-infrastructure-labs/ops-issues#11]

**Comment by ipolonsk** [comment]
Hey @larsks, I would love your help with this.
Did you document the process while setting it up for your cluster?

**Comment by larsks** [comment]
@ipolonsk the cnv cluster is configured to authenticate against the MOC sso provider (which is a Keycloak instance); you can find the configuration in the [moc-sso role](https://github.com/open-infrastructure-labs/moc-cnv-sandbox/blob/master/roles/ocp/moc-sso/tasks/main.yml).

The authorization configuration happens in the [authz role](https://github.com/open-infrastructure-labs/moc-cnv-sandbox/blob/master/roles/ocp/authz/tasks/main.yml).

**Comment by ipolonsk** [comment]
This was taken care of by @tumido and @HumairAK, thank you.
closing this issue.
