### ISSUE TITLE
Investigate sending cluster logs to loki

### ISSUE THREAD

**Issue by larsks** [open-infrastructure-labs/ops-issues#13]

**Comment by larsks** [comment]
https://meet.google.com/linkredirect?authuser=0&dest=https%3A%2F%2Fdocs.openshift.com%2Fcontainer-platform%2F4.5%2Flogging%2Fcluster-logging-external.html%23cluster-logging-external

**Comment by tumido** [comment]
https://github.com/operate-first/apps/blob/master/docs/observatorium/loki/README.md

**Comment by eranra** [comment]
@huikang @drbwa ^^^ FYI

**Comment by tumido** [comment]
Related to docs which @4n4nd  is working on, for https://github.com/operate-first/apps/issues/108 issue

**Comment by 4n4nd** [comment]
Related: https://github.com/operate-first/support/issues/44

**Comment by tumido** [comment]
https://github.com/operate-first/apps/issues/232

**Comment by HumairAK** [comment]
Accomplished and implemented in the Observatorium grafana instance here: https://grafana-opf-observatorium.apps.zero.massopen.cloud/d/liz0yRCZz/
