### ISSUE TITLE
Setup cyborg team members

### ISSUE THREAD

**Issue by goern** [open-infrastructure-labs/ops-issues#17]
- [x] invite @Sesheta as a member to the org
- [x] notify @goern to accept the invite
- [x] set visibility to 'public'
- [x] create "SourceOps" team
- [x] add sesheta to SourceOps
- [x] make SourceOps team admin for each repo

/assign @larsks
/kind feature

This is required for #16

**Comment by larsks** [comment]
@goern you are so notified.

Is "sourceops" different from [operations](https://github.com/orgs/open-infrastructure-labs/teams/operations)?

**Comment by goern** [comment]
Well, we put just the bots in that team, as they are supposed to merge PR and automated updates etc... that said... https://github.com/orgs/thoth-station/teams/sourceops/members have more members, but @sesheta would be a good start for this org

**Comment by larsks** [comment]
I've created a `sourceops` team and made @sesheta a member.

**Comment by larsks** [comment]
>  make SourceOps team admin for each repo

Is this "make sourceops team admin for *all* repos" or is this "make sourceops team admin for *specific* repos"?

**Comment by goern** [comment]
from my point of view it could be all

**Comment by larsks** [comment]
Sounds good to me. I think this is issue is resolved at this point, agreed?

**Comment by tumido** [comment]
bump @goern is this ready to be marked as resolved?
