### ISSUE TITLE
Move user management to an ArgoCD pipeline

### ISSUE THREAD

**Issue by larsks** [open-infrastructure-labs/ops-issues#2]
User management is now semi-manual (add users to playbook variables, then re-run playbooks).  Move this to a workflow that uses pull requests and is applied via argocd.

**Comment by tumido** [comment]
Will be resolved with https://github.com/operate-first/blueprint/pull/19 https://github.com/operate-first/apps/pull/120 and follow up ArgoCD applications resources.

**Comment by tumido** [comment]
Requires https://github.com/open-infrastructure-labs/ops-issues/issues/6 then it can be marked as resolved.

**Comment by tumido** [comment]
Users are managed via ArgoCD. Resources are declared here:

https://github.com/operate-first/apps/tree/master/cluster-scope/overlays/moc/groups
