### ISSUE TITLE
Test deployment of BM cluster from the current single node ACM

### ISSUE THREAD

**Issue by ipolonsk** [open-infrastructure-labs/ops-issues#23]
Try to deploy a bare-metal cluster using our single node cluster with the ACM, this task is for testing only and the cluster will be redeploy later with other tools.

**Comment by ipolonsk** [comment]
In the last few days, I have been running into a problem with the deployment,
I was able to add 3 BM nodes as assents (provides same value just like I did with install-config), but I had little problem creating and configuring a ‘provider connection’ for BM. Our current setup is a single VM on BM that runs the single node cluster and ACM, we are trying to create a cluster of our 3 other BM servers in the same local network.  

I’m not sure about the details that I need to provide for the ‘provider connection’:
- libvirt URI - not sure for which component should I give the libvirt URI, the VM, the BM server that we try to install, or the BM that holds the VM? I tried few options and every time I got an error while running the cluster creation “failed to generate asset \"Platform Provisioning Check\": platform.baremetal.libvirtURI: Internal error: could not connect to libvirt” from the hive container. (not sure how to extract the right URI that I need).
- SSH public and private keys- we just create two new pairs and copy them. 
- List of SSH known hosts - We added the main BM’s ssh public keys here to be able to connect from that server to all the new BM hosts. 

I was unable to deploy the cluster because of the libvirtURI error.

**Comment by ipolonsk** [comment]
We tried multiple values for the libvirt URI, one of them was: qemu+ssh://root@<IP>/system
running this command to check connection:
 $ virsh -c qemu+ssh://root@<IP>/system
Succeed to run it from: 
1. My local laptop (I have an ssh keys exchange with user and IP)
2. From the BM node that hosts the VM as a single node cluster and can host the bootstrap VM for the deployment process.

Tried to add the public key that we provided to the bootstrap in the ACM to the authorize_keys file where my key is located. 
But we still have the same error with 'could not connect to libvirt" and "cannot recv data: host key verification failed.: connection reset by peer"

**Comment by ipolonsk** [comment]
Use this info to enable the BM installation option: (Chris's comment from different issue) 

With RHACM 2.0, bare metal support was technical preview. So, bare metal was disabled by default. Here are the steps to enable the feature in the ui. reference: https://github.com/open-cluster-management/deploy#enabling-bare-metal-and-vmware-consoles

## Enabling Bare metal consoles
To work with bare metal, two flags need to be flipped activated

### console-header
Run the following command to enable the bare metal assets on the navigation menu

```
oc -n open-cluster-management patch deploy console-header -p \
'{"spec":{"template":{"spec":{"containers":[{"name":"console-header","env": [{"name": "featureFlags_baremetal","value":"true"}]}]}}}}'
```

### console-ui
Run the following commands to enable the bare metal button on the create cluster page

```
DEPLOY_NAME=`oc -n open-cluster-management get deploy -o name | grep consoleui`
oc -n open-cluster-management patch ${DEPLOY_NAME} -p \
'{"spec":{"template":{"spec":{"containers":[{"name":"hcm-ui","env": [{"name": "featureFlags_baremetal","value":"true"}]}]}}}}'
```

**Comment by tumido** [comment]
FTR, linking the comment from @cdoan1 mentioned ^ https://github.com/open-infrastructure-labs/ops-issues/issues/22#issuecomment-772530829

**Comment by larsks** [comment]
@ipolonsk should we close this issue (since we've moved on to the multi-node infra cluster)?
