### ISSUE TITLE
send out an email regarding cluster outage, remediation plans

### ISSUE THREAD

**Issue by goern** [open-infrastructure-labs/ops-issues#26]
create a mailing list and send out an email regarding cluster outage, remediation plans, etc.

As an Operate First operator,
I want to send out communication wrt to incidents,
so that users stay well informed about whats happening in the MOC, Operate-First infra and platform domain.

/kind feature
/priority critical-urgent
/assign @larsks

**Comment by larsks** [comment]
https://github.com/open-infrastructure-labs/mailing-lists creates a mailing list `operate-first-users@lists.massopen.cloud`, populated with the email addresses from `Users` in OpenShift.

I've run the playbook and created the list.

**Comment by tumido** [comment]
Wanna colab on the announcement email? I've started here: https://docs.google.com/document/d/1JxDeh8NKuem2zrUSeWIdCe84nCMz6DWLVwNYtyMMRkE/edit?usp=sharing

Feel free to suggest changes or additions

**Comment by tumido** [comment]
cc @HumairAK @durandom

**Comment by tumido** [comment]
Email was sent out on friday

**Comment by larsks** [comment]
@tumido so in fact, the email didn't go out; it got trapped by the fact that your `@redhat.com` address was active on the cluster so when the email was received it skipped the check for "default non-member action" and instead hit the moderation action. We should probably go ahead and re-send it, but before that, do we want to modify the language about setting up a replacement cluster?

**Comment by larsks** [comment]
@HumairAK @durandom I suspect @tumido is out for the day. Let me know if anyone has opinions on the previous comment. For reference, the content of the email is available in the google doc referenced [earlier](https://github.com/open-infrastructure-labs/ops-issues/issues/26#issuecomment-782030629).

**Comment by HumairAK** [comment]
@larsks yes I agree, we should re-send it and update the wording to mention the other cluster as well as a new date for restarting the cluster (if we still go that route).

**Comment by larsks** [comment]
I think at this point I'm going to wait until tomorrow morning before making any changes or sending out emails.

**Comment by tumido** [comment]
@larsks sure, please feel free to suggest changes to the wording in the gdoc template. :+1: I agree that it's outdated, because it's pointless announcing that some action will happen on Monday when it's already Tuesday.

> it got trapped by the fact that your @redhat.com address was active on the cluster so when the email was received it skipped the check for "default non-member action" and instead hit the moderation action

Sorry, I'm confused now. What does it mean? What do I have to do to send out emails to that mailing list? Not be logged in somewhere or how does it work?

**Comment by tumido** [comment]
:ping_pong:  @larsks

I'm afraid we still didn't sent out any email so far. What do I have to do to be able to sent the email if the issue you've mentioned above still applies?

**Comment by larsks** [comment]
@tumido I fixed your subscription last week so that you won't hit that issue again. I've also switched the default behavior to "reject" rather than "discard", which means even if something doesn't work you'll get a notification rather than having it fail silently.

**Comment by tumido** [comment]
email went out yesterday evening. Closing
