### ISSUE TITLE
Set up MOC SSO for the moc-infra cluster

### ISSUE THREAD

**Issue by tumido** [open-infrastructure-labs/ops-issues#27]
Since we have ACM available on the cluster, it would be nice if we could access it.

Related to: https://github.com/open-infrastructure-labs/ops-issues/issues/24 https://github.com/open-infrastructure-labs/ops-issues/issues/22

cc @ipolonsk @larsks

**Comment by larsks** [comment]
You can find the necessary manifests in https://github.com/open-infrastructure-labs/moc-cnv-sandbox/blob/master/roles/ocp/moc-sso/tasks/main.yml. We'll need to create an openid client id and secret. Which configuration repository is being used for the infra cluster? We'll need to encrypt the openid credentials and place them there.

**Comment by tumido** [comment]
No idea about the original config repo, I'm aiming to have that managed/tracked by ArgoCD via the operate-first/apps repo.

https://github.com/operate-first/apps/pull/271

**Comment by tumido** [comment]
Resolved via: https://github.com/operate-first/apps/pull/271
