### ISSUE TITLE
Upgrade ACM version to 2.2

### ISSUE THREAD

**Issue by ipolonsk** [open-infrastructure-labs/ops-issues#30]

**Comment by tumido** [comment]
ACM 2.2 is not released yet, correct?

**Comment by ipolonsk** [comment]
Yes, after it released.

**Comment by tumido** [comment]
BTW, can we get a beta or something maybe? Do they offer a beta channel? I think we'd like to bring our value to ACM and running the "latest and greatest" ahead of customers may be useful. :slightly_smiling_face:

**Comment by tumido** [comment]
Note: with upgrade to 2.2, ACM can automatically connect ArgoCD to the managed clusters:

https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.2/html/manage_applications/managing-applications#configuring-argo

This should actually be independent from ArgoCD operator - ACM creates a secret in the `argocd` namespace on the management cluster, which is consumable from any ArgoCD.

cc @HumairAK

**Comment by tumido** [comment]
ACM 2.2 is released and the new channel became available:

![image](https://user-images.githubusercontent.com/7453394/110124911-fd326d80-7dc2-11eb-9544-3f9d1cd0b015.png)

Based on the docs, the migration is seamless - change the channel and let it do the magic.

@larsks @ipolonsk @HumairAK wdyt, should we update now, before the `cnv -> zero` or after? I think it can bring us couple of bugfixes and make it easier for ArgoCD to pick up the new cluster (see comment above)

**Comment by tumido** [comment]
ACM successfully upgraded
