### ISSUE TITLE
Decide on a new cluster name to replace "moc-cnv" 

### ISSUE THREAD

**Issue by HumairAK** [open-infrastructure-labs/ops-issues#34]
We will need to decide on this name before the re deployment.

**Comment by HumairAK** [comment]
initial suggestion was to name our clusters with spelled out numeric suffixes like `cluster-zero`, `cluster-one`, etc.

@tumido  you had concerns over this suggestion, can you re-iterate those here

**Comment by durandom** [comment]
Because we're about to line up PRs that depend on the name.

I don't think the next cluster would necessarily be `-one`. zero would be just the [first](https://en.wikipedia.org/wiki/0) one. It could also be `-zilch`.

Or we use the DOOM universe for naming and call it `imp` or `pinky`

**Comment by tumido** [comment]
My concern with the numbering was that it implies a series. And I don't want to end up with confusing messaging again like this:

- `cluster-0` is test/toy cluster
- `cluster-1` is a prod cluster
- `cluster-2` is a prod cluster
- `cluster-3` is a test/toy cluster
etc.

If we don't make it a series and the cluster after `cluster-zero` is **not** named `cluster-one` but something else, I think that erases my concern.

**Comment by HumairAK** [comment]
okay cool, so let's go with `cluster-zero` 

@larsks can you confirm ?

**Comment by larsks** [comment]
I would vote for dropping the `cluster-` part and just calling it `zero` or `zilch` or `zed`. We know it's a cluster, and by dropping the `cluster-` part we get slightly shorter URLs every time we need to connect to a new app (`https://console-openshift-console.apps.zero.massopen.cloud/`)

**Comment by HumairAK** [comment]
Sounds good. If anyone has objections voice them here, otherwise let's go with `zero`.

**Comment by tumido** [comment]
`zero` is a good name. :slightly_smiling_face: :+1:

**Comment by HumairAK** [comment]
I think `zero` is confirmed, as it was also mentioned in the outgoing email, no take-backsies
