### ISSUE TITLE
Write ADR defining work methodology for managing Operate First sub projects

### ISSUE THREAD

**Issue by ooichman** [open-infrastructure-labs/ops-issues#35]
We want to start a new dialog about finding the right work methodology for starting and managing new sub project under the Operator first umbrella.

**Comment by durandom** [comment]
@ooichman could you explain a bit more what you consider a "sub project" and what is the "operate first umbrella"?
Do you mean just a repo in https://github.com/operate-first/ ?

**Comment by ooichman** [comment]
Hi, 
Thank you Marcel 👍🏾 
@idanlv , @ipolonsk what do you think ?

**Comment by ipolonsk** [comment]
@durandom 
As I see it, we have a few "Operate First" sub-projects like ACM, CNV, Assisted Installer that we are involved in (running on the MOC). In those projects, we would like to run the latest and greatest and perform tasks that can have value to the product development.
One each project we would like to have a task board for managing tasks and opening issues and feedback subjects. 
I want to hear other's opinions on how to create those "boards" and what is the right way to manage those projects (Create a repo/project board for each, maybe have a single board for all of those). 
@durandom, @billburnseh  what do you think?

**Comment by durandom** [comment]
I would indeed just start with a dedicated repository per project and a dedicated project board in that repository.
And then see how it works out.

We should consider where they are though. Here in open-infrastructure-labs or in operate-first - Again, no strong opinion, but regarding mindshare and name branding, I'd consider projects that operate first to be found under operate-first :)

**Comment by billburnseh** [comment]
I wonder if some projects will want to track such things in whatever they use in development (which can vary by project).
The dashboard could be a place where we can link these things. Whether we use our own task board or someone else's.  Each project has a box there and we can link to wherever that effort is tracking things. Note we don't have a populated box yet for the assisted installer...https://github.com/orgs/open-infrastructure-labs/projects/2

**Comment by tumido** [comment]
Discussed on the mtg, no ADR needed.
