### ISSUE TITLE
Install cluster for Curator project using ACM

### ISSUE THREAD

**Issue by larsks** [open-infrastructure-labs/ops-issues#36]
Gagan and Surbhi asked us for help setting  up an OCP cluster. We decided this would be a good chance to try out the baremetal support in ACM.

**Comment by larsks** [comment]
It looks as if with the configuration we're currently passing to ACM that the list of baremetal hosts isn't getting properly propagated to Ironic. The bootstrap vm comes up, but never boots any of the baremetal nodes.

We've opened https://access.redhat.com/support/cases/#/case/02884988 on this issue.

**Comment by larsks** [comment]
We ran into (and corrected) a problem with how the web UI creates the Secret with the private ssh key.

https://bugzilla.redhat.com/show_bug.cgi?id=1935411

**Comment by larsks** [comment]
Destroying a cluster in ACM after a failed install leaves the bootstrap vm running on the provisioner. This must be cleaned up manually before trying another install.

https://bugzilla.redhat.com/show_bug.cgi?id=1935792

**Comment by larsks** [comment]
Need to open a bug about:

- [x] bootstrap vm runs ironic with no password on public network

**Comment by naved001** [comment]
> Destroying a cluster in ACM after a failed install leaves the bootstrap vm running on the provisioner.

I noticed that when I had the IPI installer fail due to failed ironic inspection, the bootsrap VM was still running for me.

**Comment by larsks** [comment]
We think we've figured out why the installer wasn't able to actually start provisioning the baremetal nodes. In OCP 4.x (where `x < 8`), ACM needs access to the provisioning network on the target cluster. Naved and I are taking care of the necessary networking changes right now.

Details on this issue can be found in:

- https://bugzilla.redhat.com/show_bug.cgi?id=1935163
- https://bugzilla.redhat.com/show_bug.cgi?id=1935163
- https://github.com/openshift/installer/pull/4692

**Comment by larsks** [comment]
Re: my [earlier comment](https://github.com/open-infrastructure-labs/ops-issues/issues/36#issuecomment-791492581) about the ironic API, it looks like this has already been fixed in 4.7!

**Comment by larsks** [comment]
We are now (finally!) hitting the issue that @naved001 mentioned in which some of the hosts are detecting any local disks during inspect. I've put a copy of the ironic-inspector logs showing the inspection data [here](https://chunk.io/larsks/d4bf5b85b8f94fe2b7e1b59812909406). The inspector is only find a disk on os-controller-2. I'm going to check out he RAID config on the other hosts and see if it anything looks amiss.

**Comment by larsks** [comment]
The servers in this cluster all have two physical disks configured in a RAID1 configuration. On os-controller-0 and os-controller-1, the raid volume is in state "Operation: Back Init", with progress at 0% or 1%. I'm going to try deleting and re-creating the RAID volume.

**Comment by larsks** [comment]
Support for a variety of storage controllers was dropped in RHEL 8 and corresponding versions of RHCOS. See [here](https://access.redhat.com/solutions/3751841) for details. The list of storage controllers no longer support includes the storage controller in several of our Dell servers, identified as:

```
02:00.0 RAID bus controller [0104]: Broadcom / LSI MegaRAID SAS 2008 [Falcon] [1000:0073] (rev 03)
```

So we can't install OCP 4.x on the crc hardware. We're going to need to find different hardware.

As an aside, it looks like the hardware in the CNV cluster (shortly to become the `zero` cluster) has a different model:

```
02:00.0 RAID bus controller [0104]: Broadcom / LSI MegaRAID SAS 2208 [Thunderbolt] [1000:005b] (rev 05)
```

Looking at that Red hat article, it looks as if these models should still be supported.

@msdisme @naved001 you both may find this interesting.
