### ISSUE TITLE
Import an existing OCP cluster to ACM

### ISSUE THREAD

**Issue by ipolonsk** [open-infrastructure-labs/ops-issues#40]
As part of the HTB for ACM we are testing the option of [Import an existing cluster](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.1/html/manage_cluster/importing-a-target-managed-cluster-to-the-hub-cluster).
The cluster that we are importing is located at the PS lab behind the Red Hat VPN.

**Comment by ipolonsk** [comment]
I was able to connect the managed cluster to the ACM hub, the status is 'online'.
![image](https://user-images.githubusercontent.com/61122099/115356300-2e74ca80-a1c4-11eb-9a6f-fac5bd0cb05b.png)

**Comment by ipolonsk** [comment]
The next day I noticed that the status changed to 'offline', the managed cluster had heavy loads and the API was not reachable for periods, after fixing the heavy load on the cluster and making sure that all pods are running as usual.

We still have the status 'offline', the following errors were shown in the openshift console:
the 'klusterlet-addon-workmgr-xxxxxxx-xxxx' was is in CrashLoopBackOff status:
- event - "Search Line limits were exceeded, some search paths have been omitted, the applied search line is: open-cluster-management-agent-addon.svc.cluster.local svc.cluster.local cluster.local sales.lab.tlv.redhat.com lab.tlv.redhat.com tlv.redhat.com" 
- logs  - "unable to create controller	{"controller": "ClusterClaim", "error": "unable to create ClusterClaim: &{{ } {id.openshift.io...." 

Two resources related to the event we saw: 
- https://support.f5.com/csp/article/K18352919 
- https://bugzilla.redhat.com/show_bug.cgi?id=1857588

**Comment by ipolonsk** [comment]
Opened a Bugzilla for this issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1951490

**Comment by ipolonsk** [comment]
We noticed that the namespace 'open-cluster-management-agent' was missing from the managed cluster, investigating how this namespace got deleted (there was no human intervention).

**Comment by cdoan1** [comment]
The import process will create resources on the hub and managed cluster.

On the hub, the `managedcluster` and `klusterletaddonconfig` are created. The first represents the managed cluster state. The second defines the list of addons that will be able on the managed cluster. These resources will be in the namespace of managed cluster.

```
oc get managedcluster alex -n alex -o yaml
oc get klusterletaddonconfig alex -n alex -o yaml
```

On the managed cluster, we start up the klusterlet operator, this will run in the `open-cluster-management-agent` namespace by default. When the klusterlet operator starts up and this connects to the hub, it will create the `open-cluster-management-agent-addon` namespace and deploy the addon controllers. 

We found that we don't have the `open-cluster-management-agent` namespace , but we have the `open-cluster-management-agent-addon` namespace, at some point the agent namespace was removed, along with the klusterlet operator. Addon controllers remain.

```
oc get manifestwork alex-klusterlet -n alex -o yaml
```
Internally, we verified that it is possible to `oc delete ns open-cluster-management-agent`, thus removing the klusterlet operator, leaving the addon. This is not desirable, and we'll need to add some protection on these resources.

The error we see in the manifestwork for managed cluster indicates that the klusterlet namespace `open-cluster-management-agent` namespace no longer exists.

**Comment by cdoan1** [comment]
* The current plan is to detach/cleanup the managed cluster alex
* Then reimport and make sure we do not lose it for maybe 48 hours. If no change, then most likely the namespace was removed by accident.

**Comment by ipolonsk** [comment]
We detached the managed cluster and ran a clean-up on the managed cluster. 
In the past 3 days, the cluster was connected to the ACM and in state 'online'.

We decided we would like to reproduce the same scenario and check if the problem recurs.
We will create a heavy load on the managed cluster for few hours and monitor the namespace and the connection to ACM.

**Comment by ipolonsk** [comment]
I was unable to reproduce the same error as we saw previously, there was no change in the cluster's status over time (continue to be online.)
Closing this issue as the cluster is ready for deployment of application and other configuration via the ACM.

**Comment by ipolonsk** [comment]
I upgraded the 'alex' cluster version from 4.6.22 to 4.6.25 successfully from the ACM console.
