### ISSUE TITLE
Apply Argo CD to ilana/et al cluster

### ISSUE THREAD

**Issue by larsks** [open-infrastructure-labs/ops-issues#5]
Ilana would like to use the argocd workflow to manage their openshift cluster.

**Comment by HumairAK** [comment]
ArgoCD [was installed on Ilana's cluster](https://github.com/operate-first/continuous-deployment/pull/89), the manifests are located [here](https://github.com/operate-first/continuous-deployment/tree/master/manifests/overlays/moc-cnv).
