### ISSUE TITLE
Move forward with Argo CD to manage cluster

### ISSUE THREAD

**Issue by larsks** [open-infrastructure-labs/ops-issues#6]
Move all configuration to take advantage of argocd workflow

- [x] #3 
- [x] #2 
- [x] Ability to install operators via git workflow
- [x] #11

**Comment by HumairAK** [comment]
See #3 and #2 for the pending PR's to move this forward. 

Also, for "Ability to install operators via git workflow", we've got an ADR going for managing cluster resources, the suggestion is to have a separate ArgoCD Application that will manage cluster scope resources, operators can fall into this category. 

See [here](https://github.com/operate-first/blueprint/pull/19) for more info. 

@tumido

**Comment by HumairAK** [comment]
Currently this is blocked on the managed cluster requiring authentication, once that's done we can transfer argocd to the managed cluster.

**Comment by tumido** [comment]
I think this one can be closed as resolved.
