### ISSUE TITLE
Check comment permissions for github issues.

### ISSUE THREAD

**Issue by larsks** [open-infrastructure-labs/ops-issues#8]

**Comment by larsks-puppet** [comment]
@goern I'm not able to reproduce the problem you described -- I'm able to comment on issues from an account that is not a member of the organization.

**Comment by larsks** [comment]
(That comment was posted from a non-organizational account)

**Comment by goern** [comment]
I was talking about a card on a project that is not an issue yet...

**Comment by larsks** [comment]
I don't think there's a way to "comment" on notes in general, regardless of your organizational membership. I think they need to be converted into issues first.
