### ISSUE TITLE
Transition from ArgoCD on moc-cnv-sandbox to the ArgoCD on management cluster.

### ISSUE THREAD

**Issue by larsks** [open-infrastructure-labs/ops-issues#9]

**Comment by HumairAK** [comment]
We currently keep the argocd manifests [here](https://github.com/open-infrastructure-labs/moc-cnv-sandbox/tree/master/manifests/argocd). 

For this issue, we probably want to move these to a more general location I'd imagine. The base manifests there are nearly identical to the ones we have [here](https://github.com/operate-first/continuous-deployment/tree/master/manifests). I was thinking we just keep the argocd manifests in the operate-first/continuous-deployment repo in a new overlay directory.

**Comment by HumairAK** [comment]
This issue seems identical to: #5
Changing this issue to instead request a transition from the argocd from moc-cnv-sandbox to the new management cluster.

**Comment by tumido** [comment]
This issue is resolved, since we operate using Argo CD on the MOC infra cluster now.
